version: 2.1
workflows:
  version: 2
  test:
    jobs:
      - go1.10
      - go1.11
      - go1.12
jobs:
  go1.12: &template
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          command: |
            make
            make test
  go1.11:
    <<: *template
    docker:
      - image: circleci/golang:1.11
  go1.10:
    <<: *template
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/gsr.dev/prompt
