version: 2.1

executors:
  golang:
    parameters:
      version:
        description: Go version
        type: string
        default: latest
    docker:
      - image: circleci/golang:<< parameters.version >>

workflows:
  test:
    jobs:
      - go1.9
      - go1.10
      - go1.11
      - go1.12

jobs:
  go1.12: &template
    executors:
      - golang:
          version: 1.12
    steps:
      - checkout
      - run: make
      - run: make test

  go1.11:
    <<: *template
    executors:
      - golang:
          version: 1.11

  go1.10: &nomod_template
    <<: *template
    executors:
      - golang:
          version: 1.10
    working_directory: /go/src/gsr.dev/prompt

  go1.9:
    <<: *nomod_template
    executors:
      - golang:
          version: 1.9
