version: 2.1

executors:
  golang:
    parameters:
      version:
        description: Go version
        type: string
        default: latest
    docker:
      - image: circleci/golang:<< parameters.version >>

workflows:
  test:
    jobs:
      - go1_9
      - go1_10
      - go1_11
      - go1_12

jobs:
  go1_12: &template
    executors:
      - golang:
          version: 1.12
    steps:
      - checkout
      - run: make
      - run: make test

  go1_11:
    <<: *template
    executors:
      - golang:
          version: 1.11

  go1_10: &nomod_template
    <<: *template
    executors:
      - golang:
          version: 1.10
    working_directory: /go/src/gsr.dev/prompt

  go1_9:
    <<: *nomod_template
    executors:
      - golang:
          version: 1.9
